apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-broker
spec:
  destination:
    name: ''
    namespace: amq-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: deployment/broker
    repoURL: 'https://github.com/mamurak/amq-demo'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - Validate=false
