kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: amq-gitops
subjects:
  - kind: ServiceAccount
    name: <service account>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: amq-admin
