apiVersion: apps/v1
kind: Deployment
metadata:
  name: amq-consumer
spec:
  selector:
    matchLabels:
      app: amq-consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: amq-consumer
    spec:
      containers:
        - name: amq-consumer
          image: quay.io/mmurakam/amq-demo-consumer:latest
          envFrom:
          - configMapRef:
              name: amq-demo-client-config
