apiVersion: v1
kind: Template
metadata:
  name: amq-client-template
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: amq-demo-client-config
  data:
    BROKER_CONNECTION_URL: 'tcp://my-broker-hdls-svc:5672'
    FREQUENCY: '1.0'
    MESSAGE_ADDRESS: myqueue
- apiVersion: v1
  kind: Pod
  metadata:
    name: amq-consumer
  spec:
    containers:
    - name: amq-consumer
      image: quay.io/mmurakam/amq-demo-consumer:latest
      envFrom:
      - configMapRef:
          name: amq-demo-client-config
- apiVersion: v1
  kind: Pod
  metadata:
    name: amq-producer
  spec:
    containers:
    - name: amq-producer
      image: quay.io/mmurakam/amq-demo-producer:latest
      envFrom:
      - configMapRef:
          name: amq-demo-client-config